quarkus:
  http:
    port: 3030
  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql://localhost:5432/postgres
  hibernate-orm:
    database:
      generation: drop-and-create
