quarkus:
  http:
    port: 3030
  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql://localhost:5432/postgres
  flyway:
    migrate-at-start: true
    baseline-on-migrate: true

kafka:
  bootstrap:
    servers: PLAINTEXT://localhost:9092

mp:
  messaging:
    connector:
      smallrye-kafka:
        schema:
          registry:
            url: http://localhost:8081
    incoming:
      game-events-from-kafka:
        connector: smallrye-kafka
        topic: game-events
        value:
          deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
